spring.application.name=MynoAno

spring.datasource.url=jdbc:postgresql://localhost:5432/mynoano
spring.datasource.username=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=MYNO_SUPER_SECRET_KEY_CHANGE_THIS_TO_A_LONG_RANDOM_VALUE_123456789
jwt.expiration=86400000

logging.level.org.springframework.security=TRACE